---
services:
  qgis:
    image: qgis
    container_name: qgis
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=test123 #optional (user `abc`)
        #- CLI_ARGS= #optional
    volumes:
      - /home/dani/code/qgis-kasmvnc/tst_config:/config:z
    ports:
      - 8080:8080
      - 8181:8181
      - 8081:8081
    restart: unless-stopped
